apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1  # Number of Nginx instances
  selector:
    matchLabels:
      app: ansible
  template:
    metadata:
      labels:
        app: ansible
    spec:
      containers:
      - name: ansible
        image: ansible-image:va 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80  # Nginx listens on port 80 by default
