apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-lms-deployment
spec:
  replicas: 1  # Number of replicas
  selector:
    matchLabels:
      app: flask-lms
  template:
    metadata:
      labels:
        app: flask-lms
    spec:
      containers:
      - name: flask-lms
        image: flask-lms-image:va  # Use your Docker image name
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5003  # Flask default port
