apiVersion: v1
kind: Service
metadata:
  name: flask-lms-service
spec:
  type: NodePort  # Exposes the service outside of the cluster
  selector:
    app: flask-lms
  ports:
  - port: 5003
    targetPort: 5003
    nodePort: 30003 # Port to be exposed on the host machine
