- name: Check if Employee Service is running
  hosts: localhost
  tasks:
    - name: Check if employee_service is accessible
      uri:
        url: http://flask-es-service:5001
        method: GET
        return_content: yes
      register: es_response

    - name: Verify response for employee_service
      assert:
        that:
          - "'Welcome to the Employee Service Backend' in es_response.content"
        fail_msg: "Expected message not found in the response for Employee Service"
        success_msg: "Employee service is up and running and returned the expected message."

- name: Check if Department Service is running
  hosts: localhost
  tasks:
    - name: Check if department_service is accessible
      uri:
        url: http://flask-ds-service:5002
        method: GET
        return_content: yes
      register: ds_response

    - name: Verify response for department_service
      assert:
        that:
          - "'Welcome to the Department Service Backend' in ds_response.content"
        fail_msg: "Expected message not found in the response for Department Service"
        success_msg: "Department service is up and running and returned the expected message."

- name: Check if Leave Management Service is running
  hosts: localhost
  tasks:
    - name: Check if leave_management_service is accessible
      uri:
        url: http://flask-lms-service:5003
        method: GET
        return_content: yes
      register: lms_response

    - name: Verify response for leave_management_service
      assert:
        that:
          - "'Welcome to the Leave Management Service Backend' in lms_response.content"
        fail_msg: "Expected message not found in the response for Leave Management Service"
        success_msg: "Leave Management service is up and running and returned the expected message."
