---
- hosts: server0
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Remove default Nginx configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify:
        - restart nginx

    - name: Copy Nginx configuration template
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/myapp.conf
      notify:
        - restart nginx

    - name: Enable Nginx configuration
      file:
        src: /etc/nginx/sites-available/myapp.conf
        dest: /etc/nginx/sites-enabled/myapp.conf
        state: link
      notify:
        - restart nginx

    - name: Start Nginx if not running
      command: nginx
      ignore_errors: yes
      notify:
        - restart nginx

    - name: Check Nginx status
      command: nginx -t
      ignore_errors: yes


  handlers:
    - name: restart nginx
      command: nginx -s reload

